name: App Pre-Release

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check App version
        run: |
          APP_VERSION=$(./gradlew -q printVersionName)
          echo "APP_VERSION = " ${APP_VERSION}
